package com.sermas.x.men.model;

public enum Mutations {
    SKIP_SEND,
    SKIP_RECEIVE,
    SKIP_SEND_RECEIVE,
    SKIP_RECEIVE_SEND,
    SKIP_RECEIVE_SEND_RECEIVE,
    ADD,
    REPLACE_SUB_MESSAGES,
    REPLACE_TYPE,
    COMBINE_ADD_REPLACE_ONLY,
    COMBINE_ADD_REPLACE
}
